### ISSUE TITLE
README.* should serve as index even when it has frontmatter

### ISSUE THREAD

**Issue by jldec** [benbalter/jekyll-readme-index#1]
It's confusing for users that when they add frontmatter to a readme (e.g. to specify a layout) it stops generating index.html, even if they don't have any other files producing an index.html.

Would it make sense to adjust this logic so that README's always work like index files unless there already is another index file, or they explicitly set a different permalink?

**Comment by benbalter** [comment]
I think that makes sense. It'd be a matter of adding `|| site.pages.find { |page| page.relative_path =~ README_REGEX }` to https://github.com/benbalter/jekyll-readme-index/blob/master/lib/jekyll-readme-index/generator.rb#L25.

**Comment by ckelner** [comment]
:+1: I could use this also.

**Comment by benbalter** [comment]
If anyone is interested in submitting a pull request for this, I'd be more than glad to review it. There's some pseudo code above which may help.

**Comment by manoelcampos** [comment]
Hello, 
Is there any support for README.adoc files?
