### ISSUE TITLE
Push latest release to RubyGems.org

### ISSUE THREAD

**Issue by kylekirkby** [benbalter/jekyll-readme-index#17]
Hi @benbalter,

Could push the latest version to rubygems.org? 

BR,

Kyle

**Comment by benbalter** [comment]
https://github.com/benbalter/jekyll-readme-index/releases/tag/v0.3.0

<blockquote><img src="https://avatars0.githubusercontent.com/u/282759?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/benbalter/jekyll-readme-index">benbalter/jekyll-readme-index</a></strong></div><div>A Jekyll plugin to render a project's README as the site's index. - benbalter/jekyll-readme-index</div></blockquote>
