### ISSUE TITLE
Feature Request: allow using repo root README.md for /docs site

### ISSUE THREAD

**Issue by jrfnl** [benbalter/jekyll-readme-index#19]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

GitHub now allows a website to be generated from a subdirectory of the `master` branch.
![image](https://user-images.githubusercontent.com/663378/83319026-de52e980-a23a-11ea-92b3-e0b25cb7879f.png)

This means you end up with a directory structure like:
```
root
    - /README.md
    - /docs
        - /... other doc files
```

However, as the `README.md` file is not in the website directory, this plugin doesn't work.

### Describe the solution you'd like

If at all possible, I'd like the site's `index.html` file to be generated from the `README.md` in the project root.

I'd appreciate your consideration for this feature request.

### Describe alternatives you've considered

Using Liquid `{% include_relative ../README.md %}` won't work as that syntax [strictly forbids going up the directory tree](https://jekyllrb.com/docs/includes/#including-files-relative-to-another-file).

**Comment by benbalter** [comment]
@jrfnl have you tried using a symlink, either from the root to `docs/` or from `docs/` to the root?

**Comment by jrfnl** [comment]
@benbalter Thanks for responding. No, I haven't. I'm a Windows user, so never work with symlinks and wouldn't even know how to set that up.

**Comment by jrfnl** [comment]
Just leaving a comment to prevent the issue from being closed as the feature request still stands.

**Comment by yxwzaxns** [comment]
This is a good need, is there a way to solve it?

**Comment by jrfnl** [comment]
@yxwzaxns I haven't found one yet...

**Comment by yxwzaxns** [comment]
@jrfnl move README.md to docs/ dir, it's can be used for me.
[about github readme](urlhttps://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-readmes)
