### ISSUE TITLE
Linking explicitly to README.md should show README.md and not index.md

### ISSUE THREAD

**Issue by stevemoser** [benbalter/jekyll-readme-index#3]
Example:
https://hubwiki.github.io/test/Test.html
https://github.com/hubwiki/test/blob/master/Test.md

Expected:
The link `[Readme](README.md)` on the `Test.html` page links to `README.html` when `index.md` is present.

Actual:
The link `[Readme](README.md)` on the `Test.html` page links to `index.html` when `index.md` is present.

Or put another way: make it work like `github.com` which is the link in the preview on https://github.com/hubwiki/test/blob/master/Test.md takes you to README.md and not index.md.

**Comment by benbalter** [comment]
@stevemoser when I view the live site, `README.md` appears to link to the raw markdown, not `index.html`, no?

**Comment by stevemoser** [comment]
@benbalter You're right. I must have tested it before Pages had a chance to refresh the live site. Sorry for the interruption. Closing the issue.
