### ISSUE TITLE
It is not working for sub-folders

### ISSUE THREAD

**Issue by haschdl** [benbalter/jekyll-readme-index#9]
Hello,

It seems it works only for the root folder of the repository. Is there a way to enable all readme.md to become index.html in all folders? (I'm using Github pages)

**Comment by qwtel** [comment]
This is working for me (e.g. https://qwtel.com/hy-drawer/usage/ <--> https://github.com/qwtel/hy-drawer/tree/master/usage). 

Problem could be that the subdir already has a `index.html` file in it?
I'm also using the remove original setting

```yaml
readme_index:
  remove_originals: true
```

**Comment by haschdl** [comment]
Hi @qwtel ! I'm a bit confused, it works in one of my subfolders, but not in all.  I tried adding the `remove_originals` option, it didn't make a difference. The only option which worked was hard-coding index.html in the `permalink`, but I guess that defeats the purpose ;)
This is the readme: https://github.com/haschdl/generative/blob/master/p5jsFlashlight/readme.md

**Comment by haschdl** [comment]
Hello @qwtel
It worked only after I removed the front matter completely - including the double three dashes, which Githubs documentation says is required. Could you confirm this is the expected behavior?

**Comment by qwtel** [comment]
That's probably due to `jekyll-optional-front-matter` which is activated on GitHub Pages by default.

**Comment by kylekirkby** [comment]
I can also verify that this works for sub folders when one removes the front matter from the README.md file completely. Would anyone know what we could do to make this work with Front Matter?

Best Regards!
